FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 5002
ENV ASPNETCORE_URLS=http://*:5002

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["Netflix.Api.Ticket/Netflix.Api.Tickets.csproj", "Netflix.Api.Ticket/"]
COPY ["Netflix.Infrastructure.Abstractions/Netflix.Infrastructure.Abstractions.csproj", "Netflix.Infrastructure.Abstractions/"]
COPY ["Netflix.Infrastructure.IoC/Netflix.Infrastructure.IoC.csproj", "Netflix.Infrastructure.IoC/"]

RUN dotnet restore "Netflix.Api.Ticket/Netflix.Api.Tickets.csproj"
COPY . .
WORKDIR "/src/Netflix.Api.Ticket/."
RUN dotnet build "Netflix.Api.Tickets.csproj" -c Debug -o /app/build

FROM build AS publish
RUN dotnet publish "Netflix.Api.Tickets.csproj" -c Debug -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Netflix.Api.Tickets.dll", "--environment=Production"]
